In [88]:
import pandas as pd
import matplotlib.pyplot as plt
%matplotlib inline

In [89]:
df = pd.read_csv('Flatland_Data - Sheet1.csv', na_values="NaN", usecols = ["city", "country", "continent", "lat", "population_city", "rank_within_country"])

In [90]:
df['continent'] = df["continent"].fillna("NA")

In [91]:
df

,city,country,continent,lat,population_city,rank_within_country
0,Kisumu,Kenya,AF,-0.102,216479,5
1,Quito,Ecuador,SA,-0.230,1399814,2
2,Santo Domingo de los Colorados,Ecuador,SA,-0.253,200421,4
3,Nakuru,Kenya,AF,-0.283,259903,3
4,Fuvahmulah,Maldives,AS,-0.299,11140,2
5,Masaka,Uganda,AF,-0.334,65373,10
6,Kismayo,Somalia,AF,-0.358,234852,4
7,Garissa,Kenya,AF,-0.453,67861,9
8,Owando,Republic of the Congo,AF,-0.482,23952,5
9,Baitsi District,Nauru,OC,-0.508,810,3
10,Anabar,Nauru,OC,-0.508,378,4
11,Uaboe,Nauru,OC,-0.514,330,5
12,Ijuw,Nauru,OC,-0.521,180,6
13,Arijejen,Nauru,OC,-0.525,2381,1
14,Yaren District,Nauru,OC,-0.551,1100,2
15,Bwizibwera,Uganda,AF,-0.592,79157,6
16,Hithadhoo,Maldives,AS,-0.600,9927,3
17,Mbarara,Uganda,AF,-0.605,97500,4
18,Lambaréné,Gabon,AF,-0.700,20714,7
19,Port-Gentil,Gabon,AF,-0.719,109163,2
20,Manta,Ecuador,SA,-0.962,183166,6
21,Thika,Kenya,AF,-1.033,200000,6
22,Portoviejo,Ecuador,SA,-1.055,170326,7
23,Koulamoutou,Gabon,AF,-1.130,16222,9
24,Ambato,Ecuador,SA,-1.249,154369,10
25,Nairobi,Kenya,AF,-1.283,2750547,1
26,Belém,Brazil,SA,-1.456,1407737,10
27,Ruhengeri,Rwanda,AF,-1.500,86685,4
28,Moanda,Gabon,AF,-1.567,30151,5
29,Byumba,Rwanda,AF,-1.576,70593,6
...,...,...,...,...,...,...
2144,Kelo,Chad,AF,9.309,42533,5
2145,Parakou,Benin,AF,9.337,163753,5
2146,Colón,Panama,NA,9.355,76643,6
2147,Pala,Chad,AF,9.364,35466,7
2148,San Isidro,Costa Rica,NA,9.372,34877,8
2149,Tamale,Ghana,AF,9.401,360579,3
2150,Wotje,Marshall Islands,OC,9.454,880,5
2151,Korhogo,Ivory Coast,AF,9.458,167359,7
2152,Colonia,Micronesia,OC,9.516,7371,3
2153,Burao,Somalia,AF,9.522,99270,8
2154,Malakal,South Sudan,AF,9.533,160765,2
2155,Camayenne,Guinea,AF,9.535,1871242,1
2156,Conakry,Guinea,AF,9.538,1767200,2
2157,Kara,Togo,AF,9.551,104207,3
2158,Hargeysa,Somalia,AF,9.560,477876,2
2159,Kabala,Sierra Leone,AF,9.589,17948,9
2160,Dire Dawa,Ethiopia,AF,9.593,252279,2
2161,Jaffna,Sri Lanka,AS,9.668,169102,6
2162,Coyah,Guinea,AF,9.706,77103,7
2163,Djougou,Benin,AF,9.709,237040,3
2164,Maturín,Venezuela,SA,9.746,410972,8
2165,Likiep,Marshall Islands,OC,9.825,482,10
2166,Paraíso,Costa Rica,NA,9.838,39702,6
2167,Curridabat,Costa Rica,NA,9.912,34586,9
2168,Jos,Nigeria,AF,9.928,816824,10
2169,San José,Costa Rica,NA,9.933,335007,1
2170,San Vicente,Costa Rica,NA,9.960,34447,10
2171,Puntarenas,Costa Rica,NA,9.976,35650,7
2172,Puerto Limón,Costa Rica,NA,9.991,63081,2
2173,San Francisco,Costa Rica,NA,9.993,55923,3

In [92]:
df = df[df['continent'] != "AN"]

In [120]:
df_smallest_selection = df[(df['rank_within_country']<= 1) & (df['population_city']>2000000)]

In [121]:
df_smallest_selection['continent'].value_counts()

AS    21
AF    12
EU     7
SA     6
NA     5
OC     1
Name: continent, dtype: int64

In [122]:
# df_smallest_selection.to_csv('largest_cities.csv')

In [125]:
df_smallest_selection['population_city'].max()

22315474